export const MOCK_METRICS = {
  totalProjects: 25,
  hotProjects: 6,
  warmProjects: 5,
  staleProjects: 4,
  coldProjects: 4,
  glacierProjects: 6,
  totalTasks: 47,
  blockedTasks: 5,
  lastActivity: "2 days ago",
};

export type ProjectActivityDistribution = {
  name: string;
  value: number;
  color: string;
};

export const MOCK_ACTIVITY_DISTRIBUTION: ProjectActivityDistribution[] = [
  { name: "Hot", value: MOCK_METRICS.hotProjects, color: "#34d399" },
  { name: "Warm", value: MOCK_METRICS.warmProjects, color: "#fbbf24" },
  { name: "Stale", value: MOCK_METRICS.staleProjects, color: "#fb923c" },
  { name: "Cold", value: MOCK_METRICS.coldProjects, color: "#f87171" },
  { name: "Glacier", value: MOCK_METRICS.glacierProjects, color: "#94a3b8" },
];

import type { ActivityDataPoint } from "@/lib/types";

/** Mock activity graph: tasks completed per day over last 30 days. */
export const MOCK_ACTIVITY_GRAPH: ActivityDataPoint[] = Array.from(
  { length: 30 },
  (_, i) => {
    const d = new Date();
    d.setDate(d.getDate() - (29 - i));
    return {
      date: d.toLocaleDateString("en-US", { month: "short", day: "numeric" }),
      tasks: [
        3, 5, 2, 7, 4, 6, 3, 8, 5, 4, 6, 2, 5, 3, 4, 2, 1, 0, 1, 2, 1, 0, 0,
        1, 0, 0, 0, 1, 0, 0,
      ][i],
    };
  }
);

/** @deprecated Use MOCK_ACTIVITY_GRAPH */
export const MOCK_ACTIVITY = MOCK_ACTIVITY_GRAPH;

function daysAgo(days: number): string {
  const d = new Date();
  d.setDate(d.getDate() - days);
  return d.toISOString();
}

/** Mock ideas for Idea Inbox (timestamps relative to now). */
export const MOCK_IDEAS = [
  { id: "idea-1", text: "AI CLI for devops", createdAt: daysAgo(2) },
  { id: "idea-2", text: "macOS automation tool", createdAt: daysAgo(7) },
  { id: "idea-3", text: "rust web framework", createdAt: daysAgo(180) },
];

export const MOCK_PROJECTS = [
  {
    id: "1111",
    name: "RotDash",
    description: "Single-user web app to track project activity and detect when projects become inactive (rot). Next.js, Tailwind, ShadCN, Recharts, MongoDB.",
    tags: ["side-project", "dashboard", "nextjs"],
    status: "mvp",
    activityStatus: "hot" as const,
    rotScore: 1,
    healthStatus: "+",
    image: "https://picsum.photos/seed/rotdash/400/200",
    nextTask: "Integrate toasts",
    githubUrl: "https://github.com/vikz91/rotdash",
    prodUrl: "",
    analyticsUrl: "",
  },
  {
    id: "1",
    name: "Indie SaaS Launcher",
    description: "A launchpad for indie SaaS products with Stripe integration.",
    tags: ["saas", "side-project"],
    status: "mvp",
    activityStatus: "hot" as const,
    rotScore: 1,
    healthStatus: "+",
    image: "https://picsum.photos/seed/1/400/200",
    nextTask: "Add Stripe checkout",
    githubUrl: "https://github.com/example/indie-saas",
    prodUrl: "https://indiesaas.app",
    analyticsUrl: "",
  },
  {
    id: "2",
    name: "Discord Bot Rewrite",
    description: "TypeScript rewrite of the Discord bot with slash commands.",
    tags: ["bot", "typescript"],
    status: "idea",
    activityStatus: "warm" as const,
    rotScore: 4,
    healthStatus: "+",
    nextTask: "Fix slash command handling",
    githubUrl: "https://github.com/example/discord-bot",
    prodUrl: "",
    analyticsUrl: "",
  },
  {
    id: "3",
    name: "API Rate Limiter Lib",
    description: "Go library for API rate limiting and throttling.",
    tags: ["library", "go"],
    status: "shipped",
    activityStatus: "stale" as const,
    rotScore: 12,
    healthStatus: "-",
    image: "https://picsum.photos/seed/3/400/200",
    githubUrl: "https://github.com/example/rate-limiter",
    prodUrl: "",
    analyticsUrl: "",
  },
  {
    id: "4",
    name: "Landing Page Generator",
    description: "React-based landing page generator for indie projects.",
    tags: ["tool", "react"],
    status: "idea",
    activityStatus: "cold" as const,
    rotScore: 35,
    healthStatus: "-",
    githubUrl: "",
    prodUrl: "",
    analyticsUrl: "",
  },
  {
    id: "5",
    name: "NFT Minting Script",
    description: "Ethereum NFT minting utility script.",
    tags: ["web3", "ethereum"],
    status: "mvp",
    activityStatus: "glacier" as const,
    rotScore: 89,
    healthStatus: "-",
    image: "https://picsum.photos/seed/5/400/200",
    githubUrl: "https://github.com/example/nft-mint",
    prodUrl: "",
    analyticsUrl: "",
  },
  {
    id: "6",
    name: "CLI Todo App",
    description: "Rust CLI todo app with JSON export.",
    tags: ["cli", "rust"],
    status: "shipped",
    activityStatus: "hot" as const,
    rotScore: 0,
    healthStatus: "+",
    nextTask: "Add export to JSON",
    githubUrl: "https://github.com/example/cli-todo",
    prodUrl: "",
    analyticsUrl: "",
  },
  {
    id: "7",
    name: "Portfolio v3",
    description: "Personal portfolio website redesign.",
    tags: ["website"],
    status: "idea",
    activityStatus: "glacier" as const,
    rotScore: 120,
    healthStatus: "-",
    image: "https://picsum.photos/seed/7/400/200",
    githubUrl: "https://github.com/example/portfolio",
    prodUrl: "https://portfolio.example.com",
    analyticsUrl: "",
  },
  {
    id: "8",
    name: "React Component Library",
    description: "Design system and reusable React components.",
    tags: ["library", "design-system"],
    status: "mvp",
    activityStatus: "warm" as const,
    rotScore: 5,
    healthStatus: "+",
    githubUrl: "https://github.com/example/design-system",
    prodUrl: "",
    analyticsUrl: "",
  },
  {
    id: "9",
    name: "Email Newsletter Tool",
    description: "Newsletter management with Resend API integration.",
    tags: ["saas", "marketing"],
    status: "mvp",
    activityStatus: "hot" as const,
    rotScore: 2,
    healthStatus: "+",
    image: "https://picsum.photos/seed/9/400/200",
    nextTask: "Connect Resend API",
    githubUrl: "https://github.com/example/newsletter-tool",
    prodUrl: "https://newsletter.example.com",
    analyticsUrl: "",
  },
  {
    id: "10",
    name: "Database Migrator",
    description: "CLI tool for database migrations in Go.",
    tags: ["tool", "go", "cli"],
    status: "shipped",
    activityStatus: "warm" as const,
    rotScore: 6,
    healthStatus: "+",
    githubUrl: "https://github.com/example/db-migrator",
    prodUrl: "",
    analyticsUrl: "",
  },
  {
    id: "11",
    name: "Dark Mode Toggle Lib",
    description: "React hook and components for dark mode.",
    tags: ["library", "react", "design-system"],
    status: "idea",
    activityStatus: "stale" as const,
    rotScore: 14,
    healthStatus: "-",
    githubUrl: "https://github.com/example/dark-mode",
    prodUrl: "",
    analyticsUrl: "",
  },
  {
    id: "12",
    name: "Kanban Board MVP",
    description: "Minimal Kanban board for personal project tracking.",
    tags: ["saas", "react", "side-project"],
    status: "mvp",
    activityStatus: "cold" as const,
    rotScore: 42,
    healthStatus: "-",
    image: "https://picsum.photos/seed/12/400/200",
    githubUrl: "https://github.com/example/kanban",
    prodUrl: "https://kanban.example.com",
    analyticsUrl: "",
  },
  {
    id: "13",
    name: "GraphQL Gateway",
    description: "API gateway for GraphQL federation.",
    tags: ["backend", "api"],
    status: "shipped",
    activityStatus: "glacier" as const,
    rotScore: 95,
    healthStatus: "-",
    githubUrl: "https://github.com/example/graphql-gateway",
    prodUrl: "",
    analyticsUrl: "",
  },
  {
    id: "14",
    name: "Chrome Extension",
    description: "Productivity Chrome extension in TypeScript.",
    tags: ["browser", "typescript"],
    status: "idea",
    activityStatus: "hot" as const,
    rotScore: 0,
    healthStatus: "+",
    image: "https://picsum.photos/seed/14/400/200",
    githubUrl: "https://github.com/example/chrome-ext",
    prodUrl: "",
    analyticsUrl: "",
  },
  {
    id: "15",
    name: "Mobile App Prototype",
    description: "React Native prototype for mobile app.",
    tags: ["mobile", "react-native"],
    status: "idea",
    activityStatus: "warm" as const,
    rotScore: 8,
    healthStatus: "+",
    githubUrl: "https://github.com/example/mobile-app",
    prodUrl: "",
    analyticsUrl: "",
  },
  {
    id: "16",
    name: "PDF Generator Service",
    description: "Backend service for generating PDFs.",
    tags: ["tool", "backend"],
    status: "mvp",
    activityStatus: "stale" as const,
    rotScore: 18,
    healthStatus: "-",
    githubUrl: "https://github.com/example/pdf-gen",
    prodUrl: "",
    analyticsUrl: "",
  },
  {
    id: "17",
    name: "Test Runner UI",
    description: "Visual UI for test runner results.",
    tags: ["tool", "testing"],
    status: "idea",
    activityStatus: "cold" as const,
    rotScore: 55,
    healthStatus: "-",
    image: "https://picsum.photos/seed/17/400/200",
    githubUrl: "https://github.com/example/test-runner-ui",
    prodUrl: "",
    analyticsUrl: "",
  },
  {
    id: "18",
    name: "Deployment Scripts",
    description: "DevOps deployment automation scripts.",
    tags: ["devops", "cli"],
    status: "shipped",
    activityStatus: "glacier" as const,
    rotScore: 110,
    healthStatus: "-",
    githubUrl: "https://github.com/example/deploy-scripts",
    prodUrl: "",
    analyticsUrl: "",
  },
  {
    id: "19",
    name: "API Documentation Site",
    description: "Auto-generated API docs from OpenAPI.",
    tags: ["website", "documentation"],
    status: "mvp",
    activityStatus: "hot" as const,
    rotScore: 1,
    healthStatus: "+",
    githubUrl: "https://github.com/example/api-docs",
    prodUrl: "https://docs.example.com",
    analyticsUrl: "",
  },
  {
    id: "20",
    name: "Cache Invalidation Util",
    description: "Cache invalidation utilities for backend.",
    tags: ["library", "backend"],
    status: "idea",
    activityStatus: "warm" as const,
    rotScore: 7,
    healthStatus: "+",
    githubUrl: "https://github.com/example/cache-util",
    prodUrl: "",
    analyticsUrl: "",
  },
  {
    id: "21",
    name: "Screenshot Tool",
    description: "Desktop app for capturing screenshots.",
    tags: ["tool", "desktop"],
    status: "mvp",
    activityStatus: "glacier" as const,
    rotScore: 75,
    healthStatus: "-",
    image: "https://picsum.photos/seed/21/400/200",
    githubUrl: "https://github.com/example/screenshot-tool",
    prodUrl: "",
    analyticsUrl: "",
  },
  {
    id: "22",
    name: "Auth Middleware",
    description: "Authentication middleware for backend services.",
    tags: ["library", "backend", "security"],
    status: "shipped",
    activityStatus: "stale" as const,
    rotScore: 22,
    healthStatus: "-",
    githubUrl: "https://github.com/example/auth-middleware",
    prodUrl: "",
    analyticsUrl: "",
  },
  {
    id: "23",
    name: "Log Aggregator",
    description: "Centralized log aggregation for devops.",
    tags: ["devops", "monitoring"],
    status: "idea",
    activityStatus: "cold" as const,
    rotScore: 48,
    healthStatus: "-",
    githubUrl: "https://github.com/example/log-aggregator",
    prodUrl: "",
    analyticsUrl: "",
  },
  {
    id: "24",
    name: "Time Tracker",
    description: "Simple time tracking for productivity.",
    tags: ["saas", "productivity"],
    status: "idea",
    activityStatus: "glacier" as const,
    rotScore: 130,
    healthStatus: "-",
    githubUrl: "https://github.com/example/time-tracker",
    prodUrl: "",
    analyticsUrl: "",
  },
  {
    id: "25",
    name: "WebSocket Chat Demo",
    description: "Real-time chat demo with WebSockets.",
    tags: ["demo", "real-time"],
    status: "mvp",
    activityStatus: "hot" as const,
    rotScore: 3,
    healthStatus: "+",
    image: "https://picsum.photos/seed/25/400/200",
    githubUrl: "https://github.com/example/ws-chat",
    prodUrl: "https://chat.example.com",
    analyticsUrl: "",
  },
];

import type { Task } from "./task-schema";

export type { Task };

export const MOCK_TASKS: Task[] = [
  {
    id: "t-rotdash-1",
    projectId: "1111",
    title: "Mock dashboard page",
    description: "Summary metrics, activity chart, project grid with mock data.",
    status: "done",
    dueDate: "2025-03-01",
    completedOn: "2025-03-01",
  },
  {
    id: "t-rotdash-2",
    projectId: "1111",
    title: "Mock project view",
    description: "Project modal with project info and tasks table, inline editing.",
    status: "done",
    dueDate: "2025-03-05",
    completedOn: "2025-03-05",
  },
  {
    id: "t-rotdash-3",
    projectId: "1111",
    title: "Mock create project page",
    description: "Form/flow to create new project with required and optional fields.",
    status: "done",
    dueDate: "2025-03-07",
    completedOn: "2025-03-07",
  },
  {
    id: "t-rotdash-4",
    projectId: "1111",
    title: "Integrate toasts",
    description: "Add toast notifications (sonner or ShadCN) for user feedback on actions.",
    status: "todo",
    dueDate: "2025-03-15",
    completedOn: null,
  },
  {
    id: "t1",
    projectId: "1",
    title: "Add Stripe checkout",
    description: "",
    status: "in_progress",
    dueDate: "2025-03-15",
    completedOn: null,
  },
  {
    id: "t2",
    projectId: "1",
    title: "Setup auth flow",
    description: "",
    status: "done",
    dueDate: "2025-03-01",
    completedOn: "2025-03-02",
  },
  {
    id: "t3",
    projectId: "1",
    title: "Landing page",
    description: "",
    status: "done",
    dueDate: "2025-02-28",
    completedOn: "2025-02-27",
  },
  {
    id: "t4",
    projectId: "2",
    title: "Fix slash command handling",
    description: "",
    status: "todo",
    dueDate: "2025-03-20",
    completedOn: null,
  },
  {
    id: "t5",
    projectId: "2",
    title: "Migrate to TypeScript",
    description: "",
    status: "in_progress",
    dueDate: "2025-03-25",
    completedOn: null,
  },
  {
    id: "t6",
    projectId: "3",
    title: "Update deps",
    description: "",
    status: "todo",
    dueDate: "",
    completedOn: null,
  },
  {
    id: "t7",
    projectId: "3",
    title: "Add Redis backend",
    description: "",
    status: "todo",
    dueDate: "",
    completedOn: null,
  },
  {
    id: "t8",
    projectId: "4",
    title: "Design templates",
    description: "",
    status: "todo",
    dueDate: "",
    completedOn: null,
  },
  {
    id: "t9",
    projectId: "5",
    title: "Test on testnet",
    description: "",
    status: "blocked",
    dueDate: "2025-04-01",
    completedOn: null,
  },
  {
    id: "t10",
    projectId: "6",
    title: "Add export to JSON",
    description: "",
    status: "todo",
    dueDate: "2025-03-10",
    completedOn: null,
  },
  {
    id: "t11",
    projectId: "6",
    title: "CLI help docs",
    description: "",
    status: "done",
    dueDate: "2025-02-15",
    completedOn: "2025-02-14",
  },
  {
    id: "t12",
    projectId: "7",
    title: "Choose design direction",
    description: "",
    status: "todo",
    dueDate: "",
    completedOn: null,
  },
  {
    id: "t13",
    projectId: "8",
    title: "Button component",
    description: "",
    status: "in_progress",
    dueDate: "2025-03-12",
    completedOn: null,
  },
  {
    id: "t14",
    projectId: "8",
    title: "Input component",
    description: "",
    status: "todo",
    dueDate: "2025-03-18",
    completedOn: null,
  },
  {
    id: "t15",
    projectId: "9",
    title: "Connect Resend API",
    description: "",
    status: "in_progress",
    dueDate: "2025-03-08",
    completedOn: null,
  },
  {
    id: "t16",
    projectId: "9",
    title: "Subscriber list UI",
    description: "",
    status: "done",
    dueDate: "2025-02-28",
    completedOn: "2025-03-01",
  },
  {
    id: "t17",
    projectId: "10",
    title: "Postgres support",
    description: "",
    status: "done",
    dueDate: "2025-01-15",
    completedOn: "2025-01-14",
  },
  {
    id: "t18",
    projectId: "12",
    title: "Drag and drop",
    description: "",
    status: "blocked",
    dueDate: "2025-04-15",
    completedOn: null,
  },
  {
    id: "t19",
    projectId: "12",
    title: "Board CRUD",
    description: "",
    status: "todo",
    dueDate: "2025-03-30",
    completedOn: null,
  },
  {
    id: "t20",
    projectId: "14",
    title: "Options page",
    description: "",
    status: "todo",
    dueDate: "2025-03-22",
    completedOn: null,
  },
  {
    id: "t21",
    projectId: "19",
    title: "OpenAPI parser",
    description: "",
    status: "in_progress",
    dueDate: "2025-03-05",
    completedOn: null,
  },
  {
    id: "t22",
    projectId: "19",
    title: "Swagger UI embed",
    description: "",
    status: "done",
    dueDate: "2025-02-20",
    completedOn: "2025-02-19",
  },
  {
    id: "t23",
    projectId: "25",
    title: "Rooms support",
    description: "",
    status: "todo",
    dueDate: "2025-03-18",
    completedOn: null,
  },
  {
    id: "t24",
    projectId: "25",
    title: "Message persistence",
    description: "",
    status: "in_progress",
    dueDate: "2025-03-12",
    completedOn: null,
  },
];
