export const MOCK_METRICS = {
  totalProjects: 25,
  hotProjects: 6,
  warmProjects: 5,
  staleProjects: 4,
  coldProjects: 4,
  glacierProjects: 6,
  totalTasks: 47,
  blockedTasks: 5,
};

export type ProjectActivityDistribution = {
  name: string;
  value: number;
  color: string;
};

export const MOCK_ACTIVITY_DISTRIBUTION: ProjectActivityDistribution[] = [
  { name: "Hot", value: MOCK_METRICS.hotProjects, color: "#34d399" },
  { name: "Warm", value: MOCK_METRICS.warmProjects, color: "#fbbf24" },
  { name: "Stale", value: MOCK_METRICS.staleProjects, color: "#fb923c" },
  { name: "Cold", value: MOCK_METRICS.coldProjects, color: "#f87171" },
  { name: "Glacier", value: MOCK_METRICS.glacierProjects, color: "#94a3b8" },
];

export const MOCK_ACTIVITY = Array.from({ length: 30 }, (_, i) => {
  const d = new Date();
  d.setDate(d.getDate() - (29 - i));
  return {
    date: d.toLocaleDateString("en-US", { month: "short", day: "numeric" }),
    tasks: [3, 5, 2, 7, 4, 6, 3, 8, 5, 4, 6, 2, 5, 3, 4, 2, 1, 0, 1, 2, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0][i],
  };
});

export const MOCK_PROJECTS = [
  {
    id: "1",
    name: "Indie SaaS Launcher",
    tags: ["saas", "side-project"],
    status: "mvp",
    activityStatus: "hot" as const,
    rotScore: 1,
    healthStatus: "+",
    image: "https://picsum.photos/seed/1/400/200",
    nextTask: "Add Stripe checkout",
  },
  {
    id: "2",
    name: "Discord Bot Rewrite",
    tags: ["bot", "typescript"],
    status: "idea",
    activityStatus: "warm" as const,
    rotScore: 4,
    healthStatus: "+",
    nextTask: "Fix slash command handling",
  },
  {
    id: "3",
    name: "API Rate Limiter Lib",
    tags: ["library", "go"],
    status: "shipped",
    activityStatus: "stale" as const,
    rotScore: 12,
    healthStatus: "-",
    image: "https://picsum.photos/seed/3/400/200",
  },
  {
    id: "4",
    name: "Landing Page Generator",
    tags: ["tool", "react"],
    status: "idea",
    activityStatus: "cold" as const,
    rotScore: 35,
    healthStatus: "-",
  },
  {
    id: "5",
    name: "NFT Minting Script",
    tags: ["web3", "ethereum"],
    status: "mvp",
    activityStatus: "glacier" as const,
    rotScore: 89,
    healthStatus: "-",
    image: "https://picsum.photos/seed/5/400/200",
  },
  {
    id: "6",
    name: "CLI Todo App",
    tags: ["cli", "rust"],
    status: "shipped",
    activityStatus: "hot" as const,
    rotScore: 0,
    healthStatus: "+",
    nextTask: "Add export to JSON",
  },
  {
    id: "7",
    name: "Portfolio v3",
    tags: ["website"],
    status: "idea",
    activityStatus: "glacier" as const,
    rotScore: 120,
    healthStatus: "-",
    image: "https://picsum.photos/seed/7/400/200",
  },
  {
    id: "8",
    name: "React Component Library",
    tags: ["library", "design-system"],
    status: "mvp",
    activityStatus: "warm" as const,
    rotScore: 5,
    healthStatus: "+",
  },
  {
    id: "9",
    name: "Email Newsletter Tool",
    tags: ["saas", "marketing"],
    status: "mvp",
    activityStatus: "hot" as const,
    rotScore: 2,
    healthStatus: "+",
    image: "https://picsum.photos/seed/9/400/200",
    nextTask: "Connect Resend API",
  },
  {
    id: "10",
    name: "Database Migrator",
    tags: ["tool", "go", "cli"],
    status: "shipped",
    activityStatus: "warm" as const,
    rotScore: 6,
    healthStatus: "+",
  },
  {
    id: "11",
    name: "Dark Mode Toggle Lib",
    tags: ["library", "react", "design-system"],
    status: "idea",
    activityStatus: "stale" as const,
    rotScore: 14,
    healthStatus: "-",
  },
  {
    id: "12",
    name: "Kanban Board MVP",
    tags: ["saas", "react", "side-project"],
    status: "mvp",
    activityStatus: "cold" as const,
    rotScore: 42,
    healthStatus: "-",
    image: "https://picsum.photos/seed/12/400/200",
  },
  {
    id: "13",
    name: "GraphQL Gateway",
    tags: ["backend", "api"],
    status: "shipped",
    activityStatus: "glacier" as const,
    rotScore: 95,
    healthStatus: "-",
  },
  {
    id: "14",
    name: "Chrome Extension",
    tags: ["browser", "typescript"],
    status: "idea",
    activityStatus: "hot" as const,
    rotScore: 0,
    healthStatus: "+",
    image: "https://picsum.photos/seed/14/400/200",
  },
  {
    id: "15",
    name: "Mobile App Prototype",
    tags: ["mobile", "react-native"],
    status: "idea",
    activityStatus: "warm" as const,
    rotScore: 8,
    healthStatus: "+",
  },
  {
    id: "16",
    name: "PDF Generator Service",
    tags: ["tool", "backend"],
    status: "mvp",
    activityStatus: "stale" as const,
    rotScore: 18,
    healthStatus: "-",
  },
  {
    id: "17",
    name: "Test Runner UI",
    tags: ["tool", "testing"],
    status: "idea",
    activityStatus: "cold" as const,
    rotScore: 55,
    healthStatus: "-",
    image: "https://picsum.photos/seed/17/400/200",
  },
  {
    id: "18",
    name: "Deployment Scripts",
    tags: ["devops", "cli"],
    status: "shipped",
    activityStatus: "glacier" as const,
    rotScore: 110,
    healthStatus: "-",
  },
  {
    id: "19",
    name: "API Documentation Site",
    tags: ["website", "documentation"],
    status: "mvp",
    activityStatus: "hot" as const,
    rotScore: 1,
    healthStatus: "+",
  },
  {
    id: "20",
    name: "Cache Invalidation Util",
    tags: ["library", "backend"],
    status: "idea",
    activityStatus: "warm" as const,
    rotScore: 7,
    healthStatus: "+",
  },
  {
    id: "21",
    name: "Screenshot Tool",
    tags: ["tool", "desktop"],
    status: "mvp",
    activityStatus: "glacier" as const,
    rotScore: 75,
    healthStatus: "-",
    image: "https://picsum.photos/seed/21/400/200",
  },
  {
    id: "22",
    name: "Auth Middleware",
    tags: ["library", "backend", "security"],
    status: "shipped",
    activityStatus: "stale" as const,
    rotScore: 22,
    healthStatus: "-",
  },
  {
    id: "23",
    name: "Log Aggregator",
    tags: ["devops", "monitoring"],
    status: "idea",
    activityStatus: "cold" as const,
    rotScore: 48,
    healthStatus: "-",
  },
  {
    id: "24",
    name: "Time Tracker",
    tags: ["saas", "productivity"],
    status: "idea",
    activityStatus: "glacier" as const,
    rotScore: 130,
    healthStatus: "-",
  },
  {
    id: "25",
    name: "WebSocket Chat Demo",
    tags: ["demo", "real-time"],
    status: "mvp",
    activityStatus: "hot" as const,
    rotScore: 3,
    healthStatus: "+",
    image: "https://picsum.photos/seed/25/400/200",
  },
];
